from .main_view import MainView
from .login_view import LoginView
from .logout_view import LogoutView
from .signup_view import SignupView
from .local_view import LocalView
from .regional_view import RegionalView
from .federal_view import FederalView
from .user_view import UserView
from .add_staff_view import AddStaffView
from .change_view import ChangeView