from flask.views import View
from flask import render_template, request, redirect, url_for
from flask_login import current_user
from models import db
from models.departments import Department

class MainView(View):
    def dispatch_request(self):
        """szfo = Department(name="СЗФО", parent=None, level=1)
        db.session.add(szfo)
        cfo = Department(name="ЦФО", parent=None, level=1)
        db.session.add(cfo)
        mo = Department(name="Московская область", parent="ЦФО", level=2)
        db.session.add(mo)
        oo = Department(name="Орловская область", parent="ЦФО", level=2)
        db.session.add(oo)
        ro = Department(name="Рязанская область", parent="ЦФО", level=2)
        db.session.add(ro)
        ao = Department(name="Архангельская область", parent="СЗФО", level=2)
        db.session.add(ao)
        lo = Department(name="Ленинградская область", parent="СЗФО", level=2)
        db.session.add(lo)
        po = Department(name="Псковская область", parent="СЗФО", level=2)
        db.session.add(po)
        o = Department(name="Одинцово", parent="Московская область", level=3)
        db.session.add(o)
        nf = Department(name="Наро-Фоминск", parent="Московская область", level=3)
        db.session.add(nf)
        dd = Department(name="Домодедово", parent="Московская область", level=3)
        db.session.add(dd)
        orel = Department(name="Орел", parent="Орловская область", level=3)
        db.session.add(orel)
        mc = Department(name="Мценск", parent="Орловская область", level=3)
        db.session.add(mc)
        li = Department(name="Ливны", parent="Орловская область", level=3)
        db.session.add(li)
        shi = Department(name="Шилово", parent="Рязанская область", level=3)
        db.session.add(shi)
        pu = Department(name="Рыбное", parent="Рязанская область", level=3)
        db.session.add(pu)
        sa = Department(name="Сасово", parent="Рязанская область", level=3)
        db.session.add(sa)
        arh = Department(name="Архангельск", parent="Архангельская область", level=3)
        db.session.add(arh)
        kot = Department(name="Котлас", parent="Архангельская область", level=3)
        db.session.add(kot)
        cd = Department(name="Северодвинск", parent="Архангельская область", level=3)
        db.session.add(cd)
        ti = Department(name="Тихвин", parent="Ленинградская область", level=3)
        db.session.add(ti)
        to = Department(name="Тосно", parent="Ленинградская область", level=3)
        db.session.add(to)
        lu = Department(name="Луга", parent="Ленинградская область", level=3)
        db.session.add(lu)
        pe = Department(name="Печоры", parent="Псковская область", level=3)
        db.session.add(pe)
        ne = Department(name="Невель", parent="Псковская область", level=3)
        db.session.add(ne)
        pus = Department(name="Пустошка", parent="Псковская область", level=3)
        db.session.add(pus)
        db.session.commit()"""
        if current_user.is_authenticated:
            return redirect(url_for('user', user_id=current_user.get_id()))
        return render_template('main.html')